name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIASGDCNOFPLIEFFW2F }}
          AWS_SECRET_ACCESS_KEY: ${{ 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 }}

      - name: Notify on Success
        if: success()
        run: echo "Terraform deployment succeeded!"

      - name: Notify on Failure
        if: failure()
        run: echo "Terraform deployment failed!"

